### ISSUE TITLE
No Regex found error

### ISSUE THREAD

**Issue by Splizard** [elliotchance/c2go#10]
When running the tests, I get:
```
There is no regex for 'FunctionProtoType'.
I will print out all the lines so a regex can be created:

 0x29b1190 '__ssize_t (void *, char *, size_t)' cdecl
 0x29b1430 '__ssize_t (void *, const char *, size_t)' cdecl
 0x29b16d0 'int (void *, __off64_t *, int)' cdecl
 0x29b1810 'int (void *)' cdecl
```

**Comment by elliotchance** [comment]
Can you provide the sample of C code that contains these lines? Thanks

**Comment by sbinet** [comment]
I also get these when I run the tests of c2go.
I am on Linux 64b.

**Comment by sbinet** [comment]
e.g. with the hello world.c file

**Comment by elliotchance** [comment]
Hi @sbinet - I was able to reproduce (and fix) the error by testing against a newer version of clang. Please try again with [v0.5.0](https://github.com/elliotchance/c2go/releases/tag/v0.5.0).

**Comment by sbinet** [comment]
confirmed :)
it's fixed for me.

**Comment by elliotchance** [comment]
Great, thanks!

There is one final PR to support assert.h ( #18 ) which will be v0.6.0. I am confident that everything is working as intended so I will begin rewriting it all in pure Go. This will remove the Python dependencies and make compiling much cleaner.
