### ISSUE TITLE
can convert php source to go?

### ISSUE THREAD

**Issue by uncode** [elliotchance/c2go#113]

**Comment by elliotchance** [comment]
This project only focuses on converting C to Go, not even C++ yet.

I have throught about converting PHP to Go in the past but there are actually some even greater challenges:

1. PHP is not a typed language, so the code produced would be very ugly as every operation on a variable or argument would have to be encapsulated in a function call to determine the correct type and operation at runtime. This would be especially painful if you wanted to convert your project to Go and continue working with it as pure Go.

2. PHP comes with an enormous standard library that would be too difficult to implement. Instead 
You would have to do some tricky reflect stuff and use cgo to link to the original PHP libraries so your application would not be portable.

That being said, nothing is impossible if you have a smaller, more precise use case.
