### ISSUE TITLE
typedef struct is not supported

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#127]
In some case, we need to create more tests for this in struct.c

**Comment by Konstantin8105** [comment]
Could you clarify the code of file `struct.c`

**Comment by Konstantin8105** [comment]
**Different between `struct` and `typedef struct`.**
Let's take example:
```c
#include <stdio.h>

typedef struct tag
{
    int    a;
    double z;
} strDef;

int main()
{
	{
    struct tag s; // <--- NEED WORD "struct"
    s.a = 12;
    s.z = 0.42;
    printf("%d   %f\n", s.a, s.z);
	}
	{
    strDef s;    //  <--- NO NEED WORD "struct"
    s.a = 12;
    s.z = 0.42;
    printf("%d   %f\n", s.a, s.z);
	}
}
```

For `struct`, we have to add `struct` for each variable.
For `typedef struct` we cannot add `struct` for variable.

**Compare creating variables ast.DeclRefExpr for that 2 structures**
`struct`:
```
&ast.DeclRefExpr{Address:"0x36c78f8", Position:"col:5", Type:"struct tag", Lvalue:true, For:"Var", Address2:"0x36c7880", Name:"s", Type2:"struct tag", Children:[]ast.Node{}}
```
For `typedef struct`:
```
&ast.DeclRefExpr{Address:"0x36c8de8", Position:"col:5", Type:"strDef", Lvalue:true, For:"Var", Address2:"0x36c8d70", Name:"s", Type2:"strDef", Children:[]ast.Node{}}
```
We see the different in value `Type2` -  `"struct tag"` and `"strDef"`.

**Comment by Konstantin8105** [comment]
Wrong casting.

```c
// Tests for structures.

#include <stdio.h>
#include "tests.h"

typedef struct mainStruct{
	int constant;
} secondStruct;

int main()
{
    plan(2);

    struct mainStruct s1;
    s1.constant = 42;
    is_eq(s1.constant, 42.);

	secondStruct s2;
	s2.constant = 42;
	is_eq(s2.constant, 42.);

    done_testing();
}
```
After transpiling:
```golang
	s1.constant = 42
	if approx(float64((s1.constant)), (42)) != 0 {
		...
	}
	var s2 secondStruct
	s2.constant = 42
	if approx(noarch.ByteSliceToFloat64((s2.constant)), (42)) != 0 {
		...
	}
```

**Comment by elliotchance** [comment]
Exactly, can you put in a PR that passes the example code you just provided?

**Comment by Konstantin8105** [comment]
Now, It cannot be added, because `typedef struct` create a `convertion type bug`. So, if we add that test in project - we broke the integration test.
Now, it is not clear for me - "How to fix that".

**Comment by Konstantin8105** [comment]
I create a workaround for `typedef` like Transpiller feel `typedef struct` like a base `struct`.
Add test for that and now is Ok.
