### ISSUE TITLE
Chain Inline Assignment & Comparision

### ISSUE THREAD

**Issue by dc0d** [elliotchance/c2go#132]
For this code:

```c
#include <stdio.h>
#include "math.h"

typedef __int32_t int32;

int32 sampleFunc(int32 input) 
{
    return input * 2;
}

int32 sampleAction()
{
    int32 v = 0;
    if ((v = sampleFunc(v)) == (-1))
    {
        return -1;
    }
    return v;
}

int main()
{
    printf("Hello World\n");
    return 0;
}
```

Skipping ceremonial parts, we get:

```go
func sampleAction() int32 {
	var v int32 = int32(0)
	if (v = sampleFunc(v)) == (-1) { // syntax error
		return int32(-1)
	}
	return v
}
```

Which gives an error `syntax error: unexpected =, expecting )`, while it should be (correct, expected Go code):

```go
func sampleAction() int32 {
	var v = int32(0)
	if v = sampleFunc(v); v == (-1) { // correct form
		return int32(-1)
	}
	return v
}
```

**Comment by elliotchance** [comment]
I too ran into this issue. Unfortunately, I don't think there is an easy solution because the expressions have side effects.

In that particular example it works because the order of operations is still the same, but let's say for example we had one side effect conditional on another:

```c
if v != (-1) && (v = sampleFunc(v)) == (-1) {
```

The assignment would not be happen (or be evaluated) if `v == -1` . If there is a way to handle this case as well I'm sure there are a lot more prickly and complex examples. There needs to be a AST generic way of handling this without trying to restructure the expression.

**Comment by dc0d** [comment]
I've just seen this in bunch of C code bases. Although I did not succeed to convert any of them (and the failed cases were too much to fix).

But this chained assignment could be seen at many places - another example would be `a[10] = (a[11] = action(x, y, z))`.

And this specific pattern of `if ((variable = calc()) == value) { ... }` is something that gets repeated in some C libs.

Yet that's just was my experience with a few C libs, just to try c2go and I'm not sure if it can get generalized.

**Comment by elliotchance** [comment]
For now I think the best solution is to translate the assignments into closures, so:

`a = b` -> `func() T { a = b; return a }(b)`

Here is an example: https://play.golang.org/p/Qh2DqDZZ8R

That fixes the general case for any expression, but it's messy. We should also setup specific expressions that are known to be convertible to Go-like syntax (like you suggested):

* `if (a = b)` -> `if a = b; a`
* `if ((a = b) <op> c)` -> `if a = b; a <op> c`
* etc

**Comment by Konstantin8105** [comment]
```go
type int32 __int32_t

func sampleFunc(input int32) int32 {
        return input * 2
}
func sampleAction() int32 {
        var v int32 = int32(0)
        if (func() int32 {
                v = sampleFunc(v)
                return v
        }()) == int32((-1)) {
                return int32(-1)
        }
        return v
}
func main() {
        __init()
        noarch.Printf([]byte("Hello World\n\x00"))
        return
}
func __init() {
        stdin = noarch.Stdin
        stdout = noarch.Stdout
        stderr = noarch.Stderr
}
```
Result:
```
○ → go run 1.go
Hello World
```
That issue solve.
