### ISSUE TITLE
Repetition of CLI help message

### ISSUE THREAD

**Issue by pravj** [elliotchance/c2go#136]
When using a help flag for sub-commands, it results in duplication of the help statement.
One of them seems like a default message generated by the standard flags package.

> c2go transpile -h

```
Usage of transpile:
  -V	print progress as comments
  -o string
    	output Go generated code to the specified file
Usage: c2go transpile [-V] [-o file.go] [-p package] file.c
  -V	print progress as comments
  -o string
    	output Go generated code to the specified file
```

@jorbs, you have done an excellent job in closing #74 without using any external dependancy. 👍

**Comment by jorbs** [comment]
Hi @pravj 

Thanks for your feedback!
