### ISSUE TITLE
Provide new code samples (if you are new, start here)

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#15]
[http://www.cplusplus.com/reference/](http://www.cplusplus.com/reference/) is a great source for code samples since they have examples for most functions, like: [http://www.cplusplus.com/reference/cmath/cos/](http://www.cplusplus.com/reference/cmath/cos/)

Here's how to contribute:

1. Have the project cloned and working (run `go test -tags=integration`).
2. Put one of the samples (any sample that is a complete program and has at least one `printf()` will do) in the [tests/](https://github.com/elliotchance/c2go/tree/master/tests) directory.
3. Try to run it with: `go test -tags=integration -run TestIntegrationScripts/tests/ctype/isalnum.c`
4. Have a go at trying to fix any errors - **if you can't fix the errors, don't worry!** Even opening a PR with a broken build is helpful. The PR also acts as a great place to get feedback, ask for help, or even get someone else to help you out.

It is best to keep PRs as small as possible, so even providing a PR with the code for single function would be fantastic.

Happy coding!

**Comment by jorbs** [comment]
C `puts` function isn't translated to `fmt.Println`. I've tried the snippet below to conclude this. So I added `int puts() -> fmt.Println` in `ast/function_definition.go` in order to fix the issue. But it doesn't seem to be the right place to do those function mappings.

```int main() {
    puts("hi");
    return 0;
}```

**Comment by elliotchance** [comment]
The original description on this issue was wrong, I have updated it.

Please add a PR with `tests/stdio/puts.c`.

**Comment by elliotchance** [comment]
I am closing this because there is no way to pin it to the top, so it gets buried.
