### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#166]
I will try to test your library in according to examples https://cis.temple.edu/~ingargio/cis71/code/ .
If you want, then I will snow you the results.

**Comment by elliotchance** [comment]
I want to avoid adding lots of examples that need to be tested with every build. Apart from the fact examples slow down the build, it is also unreliable if the examples change that might introduce a regression.

I would encourage you to try running the examples locally (by putting them in the `examples` directory and running `go test`) and open an issue for each example that does not work. This makes it much easier to identify and fix each issue separately. Fixing the issues will create more exhaustive integration tests so hopefully nobody else encounters the issue :crossed_fingers: 

Cheers!

**Comment by Konstantin8105** [comment]
Ok. Thank you for clarification
