### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#167]
Hello,
Could you clarify about convert the science library [GNU GSL](https://www.gnu.org/software/gsl/).
In according to flags in main function, we cannot give the big folder with many *.c, *.h.
Have you idea about - how to solve?

Thank you.

**Comment by elliotchance** [comment]
That's correct, it only supports the transpiling of one file at the moment. We have not come to a good solution for handling multiple files yet.

See https://github.com/elliotchance/c2go/issues/63. Please comment with your thoughts.
