### ISSUE TITLE
Debug flag

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#169]
Is need the debug flag for print debug information?
For example:
```command line
c2go transpile -d myfile.c
flag -d for output debug information.
```

**Comment by elliotchance** [comment]
There is a verbose mode, but it doesn't provide much information. Maybe it would be better to have multiple levels of verbose (with the highest one being debug) that prints out everything.

We would need to define what the levels are and also what each level does.

**Comment by Konstantin8105** [comment]
Yes, you are right verbose mode and integration tests is enought for analizing.
If it is not actual, then please close.
