### ISSUE TITLE
Rating of success

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#173]
I create little rating https://github.com/Konstantin8105/c2go-rating for checking the c2go.
Also, I found flag `-o` of c2go is work , but not added in help result:
``` 
Usage: ./c2go [-v] [<command>] [<flags>] file.c

Commands:
  transpile	transpile an input C source file to Go
  ast		print AST before translated Go code

Flags:
  -v	print the version and exit
```

**Comment by Konstantin8105** [comment]
I will fix in next pull request

**Comment by elliotchance** [comment]
That's very cool! You should update the README to explain more clearly what the package is for.

I'd really appreciate it if you were to fix some of the failing files.

**Comment by Konstantin8105** [comment]
I close that, because present design with dashboard of SQLite warning is nice.
Also 90 % of simple code are ok now and don't show the problems
