### ISSUE TITLE
Preprocessor C

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#175]
Preprocessors:
#ifdef, #ifndef, #endif

Example:
```c
#ifdef WITH_GLOBALS	
 int run_kernel ( int argc, char *argv[] ) {
#endif

#ifndef WITH_GLOBALS
 int main ( int argc, char *argv[] ) {
#endif
```

#if, #elif, #endif
```c
#if SYSTEM_1
# include "system_1.h"
#elif SYSTEM_2
# include "system_2.h"
#elif SYSTEM_3
...
#endif
```

#define, #undef 
#include

We don`t think about preprocessor, because clang take all work with preprocessor.

**Comment by elliotchance** [comment]
Correct. The preprocessor happens before clang generates the AST so we don't need to worry about any of these. Was there a question or concern in this issue?
