### ISSUE TITLE
Parallel integration test

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#178]
Now, project have `/build`. All integration tests checked in that folder. May we delete that folder?
In my point of view, we can create integration test in parallel, if we use use not single folder. How I fell that in `main_test.go` in function `TestIntegrationScripts`?
1. Create many temp folders with name /build1/, /build2/,..
2. Run test. "One folder per one test".
3. remove temp folders.

**Comment by elliotchance** [comment]
The `build` directory is temporary and not committed to git. It contains build assets that can be regenerated.

Do not create more folders in the root. You could create subfolders but you would not want to run all tests at the same time - carefully choose the right amount of parallel tests for the number of CPUs available.

**Comment by Konstantin8105** [comment]
I add a one code line for delete this folder after integration test.
If I will find the solution with parallel testing, then I will remove all temporary folders for save clean project.

**Comment by elliotchance** [comment]
@Konstantin8105 I appreciate the work you are doing but you can't make lots of random changes to the same PR ongoing forever. You must create a PR for each issue. Once you open that PR it must be ready for review and merge (no more changes required)

**Comment by Konstantin8105** [comment]
Ok,

**Comment by Konstantin8105** [comment]
After experiments:
```
Without parallel:
Time for clang -lm is: 282.935431ms
Time for run c code is: 2.008996ms
Time for run "go build" is: 2.726436273s
TAP: # tests/math.c: 359 tests

With parallel:
Time for clang -lm is: 267.343816ms
Time for run c code is: 2.225319ms
Time for run "go build" is: 2.639330105s
TAP: # tests/math.c: 359 tests
```
So, most of time going for "go build", and add parallel of testing is not effective.

**Comment by Konstantin8105** [comment]
Now, I have a branch on my fork repo with subfolders for each test. Navigation with that separation is better, but for better look result of integration test use:
```
rm -r ./build ; go test -tags=integration ./...
```
I will create the pull request about that later.

**Comment by elliotchance** [comment]
I'm fine with putting each test in a subfolder if that makes it easier to see the output. However, I don't understand what you mean by "So, in my point of view, I remove "Remove" folder from code."?

**Comment by Konstantin8105** [comment]
Now, I cannot remember - What I mean :)
In my point of view, we can close that issue
