### ISSUE TITLE
Presentation on README

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#182]
We can create a simply ascii video of c2go work and show on README page.
Link: https://asciinema.org/

Examples of looking:
https://github.com/asciinema/asciinema
https://github.com/paoloantinori/hhighlighter

Scenario:
1. Text `# Demo c2go`
2. Command `ls` show list of files:
```
> ls
hello.c c2go
```
3. Show the C code, command `cat hello.c`
4. Transpiling. Command `./c2go transpile hello.c'
5. Show list of files `ls`:
```
> ls
hello.c hello.go c2go
```
6. Run Go code. Command `go run hello.go`

**Comment by Konstantin8105** [comment]
Prototype:
https://asciinema.org/a/R4Acgdxmxjdrm5tXVhlWWGdnK

**Comment by elliotchance** [comment]
That's interesting. However, c2go isn't an interactive tool that needs to be demonstrated. What do others think?

**Comment by Konstantin8105** [comment]
At the end of website page, we will see the demo of that software recorded by asciinema.
If it not nessesary for c2go, then we can close the issue.

**Comment by elliotchance** [comment]
Maybe this will be something we revisit in the future, but I will close it for now.
