### ISSUE TITLE
nil Error patter

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#187]
Typical pattern for error is:
```golang
stmts, st, newPre, newPost, err := transpileToExpr(n.Children[0], p)
if err != nil {
return nil, "", nil, nil, err
}
```
What we can do with that:
1. If error is error, then we can add Warning about that error
2. If error is not error, then we can add coverage test for that case.

**Comment by elliotchance** [comment]
Please explain further why this issue was raised?
