### ISSUE TITLE
CLI testing

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#190]
As we get more CLI options being able to test them will become more and more important.

We should create integration tests that test the output of the binary with certain flags.

This does not have to be in `go test` straight away, bash will do just fine for now. One idea:

1. Run c2go and output to a file, like `c2go --help > out.txt`
2. Compare the output to a known output file, like `cmp --silent out.txt cli_tests/help.txt`

**Comment by Konstantin8105** [comment]
Could you clarify- is it done?
Because now we use snapshots for cli commands

**Comment by elliotchance** [comment]
Yes, I'm happy to close this. Any further issues can be opened as another issue.
