### ISSUE TITLE
Error stack trace

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#192]
If we add recovery-panic snippet like on example:
```golang
	// Error stack trace
	defer func() {
		if err := recover(); err != nil {
			err = fmt.Errorf("transpileToNode\nnode = %#v\nError: %v\n", node, err)
			panic(err)
		}
	}()
```

Maybe we will have a lot of error clarification.

Let's take for example of C source - `kilo.c` https://github.com/Konstantin8105/c2go-rating/blob/master/SingleCcode/kilo.c
Example of error output after adding in file `transpiler.go`:
Before:
```
Error: panic: invalid identity: 'Not[]erow'
```
After
```
Error: panic: invalid identity: 'Not[]erow' [recovered]
	panic: transpileToExpr
node = &ast.UnaryOperator{Address:"0x2cd8748", Position:"line:688:9, col:10", Type:"int", IsLvalue:false, IsPrefix:true, Operator:"!", Children:[]ast.Node{(*ast.ImplicitCastExpr)(0xc42058f020)}}
 [recovered]
	panic: transpileToStmt
node = &ast.IfStmt{Address:"0x2cd8a58", Position:"line:688:5, line:691:5", Children:[]ast.Node{ast.Node(nil), (*ast.UnaryOperator)(0xc42058ee40), (*ast.CompoundStmt)(0xc4203e19c0), ast.Node(nil)}}
 [recovered]
	panic: transpileToStmts
node = &ast.IfStmt{Address:"0x2cd8a58", Position:"line:688:5, line:691:5", Children:[]ast.Node{ast.Node(nil), (*ast.UnaryOperator)(0xc42058ee40), (*ast.CompoundStmt)(0xc4203e19c0), ast.Node(nil)}}
 [recovered]
	panic: transpileToStmt
node = &ast.CompoundStmt{Address:"0x2cd9088", Position:"col:30, line:699:1", Children:[]ast.Node{(*ast.DeclStmt)(0xc4202915c0), (*ast.DeclStmt)(0xc420017240), (*ast.DeclStmt)(0xc4200c5880), (*ast.IfStmt)(0xc4203e1000), (*ast.BinaryOperator)(0xc42058f9e0), (*ast.CallExpr)(0xc42000ecd0), (*ast.IfStmt)(0xc4205a2180), (*ast.UnaryOperator)(0xc4202e0d20)}, BelongsToSwitch:false}
 [recovered]
	panic: transpileToStmts
node = &ast.CompoundStmt{Address:"0x2cd9088", Position:"col:30, line:699:1", Children:[]ast.Node{(*ast.DeclStmt)(0xc4202915c0), (*ast.DeclStmt)(0xc420017240), (*ast.DeclStmt)(0xc4200c5880), (*ast.IfStmt)(0xc4203e1000), (*ast.BinaryOperator)(0xc42058f9e0), (*ast.CallExpr)(0xc42000ecd0), (*ast.IfStmt)(0xc4205a2180), (*ast.UnaryOperator)(0xc4202e0d20)}, BelongsToSwitch:false}
```
So, let`s analyze:
1. We have panic with body : `Error: panic: invalid identity: 'Not[]erow'`
2. Before that panic we in `func transpileToExpr` with input data:
```
panic: transpileToExpr
node = &ast.UnaryOperator{Address:"0x2cd8748", Position:"line:688:9, col:10", Type:"int", IsLvalue:false, IsPrefix:true, Operator:"!", Children:[]ast.Node{(*ast.ImplicitCastExpr)(0xc42058f020)}}
``` 
and more...

Is acceptable to adding that error stack trace?
I hope it is helpful for analasing the real code error in project https://github.com/Konstantin8105/c2go-rating .

## Minus

* Error is very large
* Error stack trace don't clarify errors from function `func (p *Program) String() string{...}` https://github.com/elliotchance/c2go/blob/master/program/program.go#L161

## Plus

* We have large error stack trace for analyse

**Comment by elliotchance** [comment]
We should remove anywhere that a panic happens when processing code. These were left over from how lazy error handling used to be done. The goal now is to always produce Go output and try to provide as useful warnings as possible in the output file.

How about we look into why these panics are occurring in the first place?

**Comment by Konstantin8105** [comment]
Now, we don't use panic-recovery pattern (in according to our last discussions), so, that issue is not actual for myself.
If it is not actual for you, then please close.
