### ISSUE TITLE
For golang/go

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#193]
Now, typically error looks like that:
```
Error: panic: format.Node internal error (121:42: expected ']', found '+=' (and 10 more errors))

goroutine 1 [running]:
github.com/elliotchance/c2go/program.(*Program).String(0xc42048c460, 0x17, 0x5b238b)
	/home/konstantin/Documents/GoProjects/src/github.com/elliotchance/c2go/program/program.go:222 +0x20e
main.Start(0x0, 0x7fff3d2b310c, 0x17, 0x7fff3d2b30f3, 0x18, 0x5b238b, 0x4, 0xc420012380, 0xc42008a048)
	/home/konstantin/Documents/GoProjects/src/github.com/elliotchance/c2go/main.go:182 +0xae3
main.main()
	/home/konstantin/Documents/GoProjects/src/github.com/elliotchance/c2go/main.go:276 +0x373
```

One important think - we see `expected ']', found '+=' (and 10 more errors)`. But what the 10 error? It is not clear.
Like I understood, that simplification of error from that code (I am not sure, need time to be sure) https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/go/scanner/errors.go 

```golang
// An ErrorList implements the error interface.
func (p ErrorList) Error() string {
	switch len(p) {
	case 0:
		return "no errors"
	case 1:
		return p[0].Error()
	}
	return fmt.Sprintf("%s (and %d more errors)", p[0], len(p)-1)
}
```

For clarification that 10 error we can choose:
1. Download source of Go. Change that code. Compile and use personal build of Go.
2. Or Create issue for golang for change that.

@elliotchance Please clarify your opinion

### Reason

If we have folder with C code (like https://github.com/Konstantin8105/c2go-rating) and that clarification of error, then we can choose priority for project `c2go`

**Comment by elliotchance** [comment]
I'm not sure what your question is here? Do you want to see the other 10 errors?

**Comment by Konstantin8105** [comment]
Yes, in my point of view - that in important for error classification.
I will try 1 way after solving Comma problem for operators FOR and IF.

**Comment by Konstantin8105** [comment]
Now, It is not actual for myself. Because understood little bit more about project detail.
If it is not actual for you, then we can close the issue.
