### ISSUE TITLE
IndirectFieldDecl

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#195]
In according to transpiling file [`sqlite/shell.c`](https://github.com/Konstantin8105/c2go-rating/blob/master/sqlite/shell.c) of sqlite.
We have error:
```
panic: unknown node type: 'IndirectFieldDecl 0x2be19a8 <line:167:25> col:25 implicit fpstate 'struct _fpstate *''
```

**Comment by elliotchance** [comment]
You will need to create a new `indirect_field_decl.go` and `indirect_field_decl_test.go` like the other AST nodes in the `ast` package.

**Comment by Konstantin8105** [comment]
Could you clarify - Where you take the pattern for that element?

**Comment by elliotchance** [comment]
See #203
