### ISSUE TITLE
Implement qsort()

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#222]

**Comment by Konstantin8105** [comment]
Just link http://www.cplusplus.com/reference/cstdlib/qsort/?kw=qsort

**Comment by elliotchance** [comment]
Thanks for the link. `qsort` requires c2go to understand function pointers first.

**Comment by yulvil** [comment]
Depends on #157 Support function pointers

**Comment by Konstantin8105** [comment]
Please clarify - That is the issue in detail?
I see 2 different ways:
1) Just create function `noarch.Qsort()` in Go and if user code used `qsort()`, then redirect to Go implementation.
2) Create enough and transpilating function `qsort()` from system header `stdlib.h`.

If we merge #273 , then we will follow by way 2 and no need to think about of implementation `qsort` in C system header.

**Comment by carstenhag** [comment]
#157 has been resolved, can be implemented now I guess?

**Comment by elliotchance** [comment]
It sounds like @carstenhag wants to handle this one 😄

**Comment by Konstantin8105** [comment]
```
void qsort (void* base, size_t num, size_t size, int (*compar)(const void*,const void*));
```

Example:
```c
/* qsort example */
#include <stdio.h>      /* printf */
#include <stdlib.h>     /* qsort */

int values[] = { 40, 10, 100, 90, 20, 25 };

int compare (const void * a, const void * b)
{
  return ( *(int*)a - *(int*)b );
}
int main ()
{
  int n;
  qsort (values, 6, sizeof(int), compare);
  for (n=0; n<6; n++)
     printf ("%d ",values[n]);
  return 0;
}
```

**Comment by Konstantin8105** [comment]
Try to analyze https://github.com/rsc/c2go/blob/master/qsort.go for qsort implementation #222

**Comment by Konstantin8105** [comment]
Need for #67

**Comment by Konstantin8105** [comment]
We can try to use sorting from Go standard library:
https://golang.org/pkg/sort/#example_SliceStable

**Comment by Konstantin8105** [comment]
Apple source implementation specific:
https://opensource.apple.com/source/Libc/Libc-339/stdlib/FreeBSD/qsort.c

**Comment by Konstantin8105** [comment]
Apple source implementation specific:
https://opensource.apple.com/source/Libc/Libc-339/stdlib/FreeBSD/qsort.c
