### ISSUE TITLE
Support StmtExpr

### ISSUE THREAD

**Issue by hnsl** [elliotchance/c2go#230]
https://clang.llvm.org/doxygen/classclang_1_1StmtExpr.html

**Comment by elliotchance** [comment]
Do you have an example piece of code that produces a panic?

**Comment by hnsl** [comment]
I assume just transpiling something with a StmtExpr will cause this. E.g:

int a = ({ 1; })

**Comment by elliotchance** [comment]
A fix has been released: https://github.com/elliotchance/c2go/releases/tag/v0.16.2

**Comment by hnsl** [comment]
Thanks!
