### ISSUE TITLE
Array not initialized properly

### ISSUE THREAD

**Issue by yulvil** [elliotchance/c2go#250]
```
#include <stdio.h>

int main(int argc, char* argv[]) {
        argc = argc;

   int arr[] = {2,3,4};
   //arr[0] = 2;
   //arr[1] = 3;
   //arr[2] = 4;
   printf("%d\n", arr[0]);
   printf("%d\n", arr[1]);
   printf("%d\n", arr[2]);
}
```

The array initialization is translated to `var arr []int = make([]int, 3, 3)`

This will print

```
0
0
0
```

**Comment by elliotchance** [comment]
Thanks for raising this bug @yulvil - would you like to fix it?

**Comment by yulvil** [comment]
@elliotchance Hi. I'll be happy to give it a try. I have not look much at the source code yet.

**Comment by elliotchance** [comment]
You will want to have a look at this function: https://github.com/elliotchance/c2go/blob/master/transpiler/variables.go#L66

If you detect the value one of `a.Children()` you can translate that into a piece of Go AST, like it does with `make`: https://github.com/elliotchance/c2go/blob/master/transpiler/variables.go#L80
