### ISSUE TITLE
typedef struct without name

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#261]
Example from `stdlib.h`:
```c
typedef struct
  {
    int quot;           /* Quotient.  */
    int rem;            /* Remainder.  */
  } div_t;
```

Not it is look not correct:
```golang
type div_t noarch.DivT
```

**Comment by elliotchance** [comment]
This is correct because `div_t` is a type that is shared between the `noarch` package and the program, so we have to replace the type: https://github.com/elliotchance/c2go/blob/master/types/resolve.go#L58
