### ISSUE TITLE
Fix partial array initialization

### ISSUE THREAD

**Issue by yulvil** [elliotchance/c2go#262]
`int a[4] = {10, 20};` should be initialized as `{10, 20, 0, 0}`

```
currently transpiles to: var a []int = []int{nil, 10, 20}
error: cannot convert nil to type int
```

C99 specs: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf, page 127, item 21

```
If there are fewer initializers in a brace-enclosed list than there are elements or members
of an aggregate, or fewer characters in a string literal used to initialize an array of known
size than there are elements in the array, the remainder of the aggregate shall be
initialized implicitly the same as objects that have static storage duration.
```

**Comment by elliotchance** [comment]
Excellent reference! 👍

**Comment by yulvil** [comment]
@elliotchance It turns out that go behaves the same way in terms of partial array initialization. The rest of the array is assigned the zero-value for that type. The keyword here is *array*.

The problem is that we convert C arrays to Go slices.

Go https://play.golang.org/p/g2XcSacYz5
```
var a [4]int = [4]int{10,20}
fmt.Println(a[0],a[1],a[2],a[3]) // -> 10 20 0 0
```

If we convert arrays to slices (current c2go behavior):
```
var a []int = []int{nil, 10, 20} // nil is the ArrayFiller
fmt.Println(a[0],a[1],a[2],a[3]) // -> 1 2 <arrayOutOfBounds>
```

Should we convert C fixed arrays as Go fixed arrays instead of slices?

**Comment by elliotchance** [comment]
Hmmm you bring up a good point. Fixed size arrays will have to be equivalent (fixed size) in Go, otherwise assigning to an index in the capacity would fail terribly. The alternative (to simplify pointers) is we could always use slices, but have slices preallocated when created.

**Comment by yulvil** [comment]
I think it is ok to use slices for pointers and strings, but my first impression is to convert C fixed-sized arrays to go fixed-sized arrays.

I did not see that many partial initialization (like in the example), so I will refrain from making any changes until we confirm that it is necessary to transpile sqlite3.c.

I would label this issue as a "low".
