### ISSUE TITLE
Not allowable C function for Go

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#287]
Example of C code:
```c
#include <stdio.h>
void _(){
        printf("Hello");
}
int main(){
        _();
        return 0;
}
```
Result after transpilation:
```go
func _() {
        noarch.Printf([]byte("Hello\x00"))
}
func main() {
        __init()
        _()
        return
}
func __init() {
}
```
Error:
```
$ go run u.go
# command-line-arguments
./u.go:115:3: cannot use _ as value
```

**Comment by Konstantin8105** [comment]
### Question
What name we will choose for function, instead of `_`?

**Comment by elliotchance** [comment]
Good question, maybe a double underscore (`__`)? Also add a warning to the top of the file that the function has been renamed.

**Comment by Konstantin8105** [comment]
Interesting https://golang.org/ref/spec:
```
break        default      func         interface    select
case         defer        go           map          struct
chan         else         goto         package      switch
const        fallthrough  if           range        type
continue     for          import       return       var
```
What about that names? Anybody known?
Problem only if  function name is allowable for C, but not for Go function name.

**Comment by elliotchance** [comment]
We do in fact check for reserved words: https://github.com/elliotchance/c2go/blob/c324c1aec2912533de9b89eed02bd741fe4f51e4/util/goast.go#L293-L308

An underscore after the name may be more appropriate, otherwise it we need to export these entities later the first letter must be a capital.
