### ISSUE TITLE
panic on empty for-loop conditions

### ISSUE THREAD

**Issue by jnjackins** [elliotchance/c2go#29]
```for (;;)``` is legal C, but currently causes a panic. For example, in the following program, c2go attempts to treat the print statement as the initialization part of the loop condition.

```C
main(int argc, char **argv)
{
	for (;;)
		print("y\n");
}
```

**Comment by jnjackins** [comment]
It looks like there needs to be some special casing around handling of null nodes during AST parsing.

If I comment out the section of main.go that removes <<<NULL>>> from the AST, then I get the following, for ```for(;;) print("foo")```:

```
|   `-ForStmt 0x7fd828076c18 <line:3:2, col:19>
|     |-<<<NULL>>>
|     |-<<<NULL>>>
|     |-<<<NULL>>>
|     |-<<<NULL>>>
|     `-CallExpr 0x7fd828076bd0 <col:11, col:19> 'int'
|       |-ImplicitCastExpr 0x7fd828076bb8 <col:11> 'int (*)()' <FunctionToPointerDecay>
|       | `-DeclRefExpr 0x7fd828076b08 <col:11> 'int ()' Function 0x7fd828076a60 'print' 'int ()'
|       `-ImplicitCastExpr 0x7fd828076c00 <col:17> 'char *' <ArrayToPointerDecay>
|         `-StringLiteral 0x7fd828076b68 <col:17> 'char [1]' lvalue ""
```

And the following for ```for(1;1;1) print("foo")```:

```
|   `-ForStmt 0x7fad58076c78 <line:3:2, col:22>
|     |-IntegerLiteral 0x7fad58076a40 <col:7> 'int' 1
|     |-<<<NULL>>>
|     |-IntegerLiteral 0x7fad58076a60 <col:9> 'int' 1
|     |-IntegerLiteral 0x7fad58076a80 <col:11> 'int' 1
|     `-CallExpr 0x7fad58076c30 <col:14, col:22> 'int'
|       |-ImplicitCastExpr 0x7fad58076c18 <col:14> 'int (*)()' <FunctionToPointerDecay>
|       | `-DeclRefExpr 0x7fad58076b68 <col:14> 'int ()' Function 0x7fad58076ac0 'print' 'int ()'
|       `-ImplicitCastExpr 0x7fad58076c60 <col:20> 'char *' <ArrayToPointerDecay>
|         `-StringLiteral 0x7fad58076bc8 <col:20> 'char [1]' lvalue ""
```

**Comment by jnjackins** [comment]
Side note: why is there an extra ```<<<NULL>>>``` in both cases?

**Comment by elliotchance** [comment]
That's a good question, I don't know what the extra `<<<NULL>>>` are supposed to mean, but I ignore them when parsing: https://github.com/elliotchance/c2go/blob/master/main.go#L26-L30

This always gives me three parts for the for loop: https://github.com/elliotchance/c2go/blob/master/for_stmt.go#L30-L32

However, as you say, if there are less than three parts then that code would not work. Mind submitting a patch with the test C file?
