### ISSUE TITLE
Implement memset, memcpy

### ISSUE THREAD

**Issue by yulvil** [elliotchance/c2go#293]
memset can be called on any memory address, the most common being (in no specific order):
1 basic type (&int, &float, ...)
2 array of basic type
3 union/struct
4 array of union/struct

memset is usually called with 0x00, but sqlite has a few cases where the value is not 0x00

[1] and [2] are relatively easy to implement.

For [3] and [4] we can think of adding a `void (* thisStruct) Memset(...)` method with an empty body (to be filled later for corectness).

In a second phase we could implement memset/memcpy for use cases other than [1], [2], [3] and [4]

**Comment by elliotchance** [comment]
I'm fine with that. I'd rather something be partly implemented for some cases than none at all.

**Comment by Konstantin8105** [comment]
Just liks:
http://www.cplusplus.com/reference/cstring/memset/
http://www.cplusplus.com/reference/cstring/memcpy/

**Comment by kamphaus** [comment]
#### WIP:
I am working on this issue in branch [kamphaus/c2go:kamphaus:fix-293-memset-memcpy](/kamphaus/c2go/tree/fix-293-memset-memcpy).
However my code depends on #682
and I encountered #683
