### ISSUE TITLE
Remove tmp files in stdio.c

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#299]
Typically in file `stdio.c`:
```c
//....
void test_fopen()
{
    FILE *pFile;
    pFile = fopen("/tmp/myfile.txt", "w");
    if (pFile != NULL)
    {
        is_not_null(pFile);
        fclose(pFile);
    }
}
//....
```
File created, but not removed.
May be we will add removing temp file in C code.

I wrote about that, because on my laptop, I have to remove that temp file before each integration test and if I don't remove, then `go test` show a error.

**Comment by elliotchance** [comment]
Yes. that is a good point. We should really randomise the file names in test so they can never collide. And also delete the files as well.

**Comment by Konstantin8105** [comment]
Randomizing of file name is no need, tests inside file `stdio.c` not run in parallel.
