### ISSUE TITLE
syntax error: unexpected short

### ISSUE THREAD

**Issue by xyproto** [elliotchance/c2go#3]
When running `./run-tests.sh` I get:

```
~/clones/c2go% ./run-tests.sh 
argv.c
# command-line-arguments
./out.go:12: syntax error: unexpected short after top level declaration
./out.go:16: syntax error: unexpected long after top level declaration
./out.go:22: syntax error: unexpected short after top level declaration
./out.go:24: syntax error: unexpected short after top level declaration
./out.go:26: syntax error: unexpected int after top level declaration
./out.go:30: syntax error: unexpected long after top level declaration
./out.go:32: syntax error: unexpected long after top level declaration
./out.go:36: syntax error: unexpected long after top level declaration
./out.go:40: syntax error: unexpected long after top level declaration
./out.go:42: syntax error: unexpected long after top level declaration
./out.go:42: too many errors
1,3d0
< Number of command line arguments passed: 3
< 2. Command line argument passed is some
< 3. Command line argument passed is args
```

This is after changing "python" to "python2" in `run-tests.sh`.

I'm on 64-bit Arch Linux with:

* Python 2.7.13
* Python 3.6.
* Go 1.8
* clang 3.9.1
* python-libclang 3.8.2

**Comment by elliotchance** [comment]
Truth be told, I'm not sure how it was even setup on Mac, so I wasn't able to setup the travis branch, yet (#1) which would have probably fixed this issue.

I am working overhauling the clang ast to produce a JSON file that can be consumed by this script rather than using the Python clang bindings (which I believe are now deprecated). I will be able to push something soon.

In the meantime do you think you could provide any more details, such as the `out.go` it has generated?

**Comment by elliotchance** [comment]
Hi @xyproto, see the response here: https://github.com/elliotchance/c2go/issues/4

**Comment by qarth** [comment]
Hey elliot,
When I run run_tests.sh it cannot find the json which it is trying to decode.
see:
```
synths@ubuntu:~/elliotchance/2/c2go-0.2.0$ ./run-tests.sh 
argv.c
Traceback (most recent call last):
  File "c2go.py", line 517, in <module>
    render(go_out, json.loads(json_in.read())[0])
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
package main: 
out.go:1:1: expected 'package', found 'EOF'
1,3d0
< Number of command line arguments passed: 3
< 2. Command line argument passed is some
< 3. Command line argument passed is args
```
Any ideas?

**Comment by elliotchance** [comment]
Yes, I know what that is. I have been testing it on my mac, but the clang AST (or perhaps its just the different version of clang) on linux outputs slightly differently. I am almost finished fixing those issues in #6 which once green will be tagged as v0.3.0.

v0.3.0 will have support for both mac and linux, however in the future this error will still appear as the test programs get more complicated and expose more node types on the AST. The plan is to have a build matrix testing all minor versions of clang tested against several operating systems.

http://stackoverflow.com/questions/43012819/how-do-i-specify-the-python-version-with-a-cpp-project-in-travis-ci

In a long roundabout way I am saying that there error handling is very poor right now and if you could offer any improvements that would be fantastic 😄

**Comment by elliotchance** [comment]
@qarth please try again with v0.3.0

**Comment by elliotchance** [comment]
This has been fixed for a while now - also there is no more Python.
