### ISSUE TITLE
Make regexp non-greedy

### ISSUE THREAD

**Issue by yulvil** [elliotchance/c2go#312]
I profiled c2go and saw that it was spending a lot of time doing regexp backtracking.

We are currently using `.*` (greedy) or `.*?` (non-greedy) when parsing the AST.

We should use the closing character instead to determine where the group stops, i.e. instead of `.*` use `[^>]*` or `[^']*`

For example, replace
```
(?P<address>0x[0-9a-f]+) <(?P<position>.*)>'(?P<type1>.*?)'(:'(?P<type2>.*)')? lvalue
```
by
```
(?P<address>0x[0-9a-f]+) <(?P<position>[^>]*)>'(?P<type1>[^']*)'(:'(?P<type2>[^']*)')? lvalue
```

On https://regex101.com/ this is cutting down the number of steps to match by 50 to 75%.

I will try to do a global search and replace to see if it improves the performance.
```
>.*)>  ->  >[^>]*>
>.*?)>  ->  >[^>]*>
>.*)'  -> >[^']*)'
>.*?)'  -> >[^']*)'
>.*)"  -> >[^"]*)"
>.*?)"  -> >[^"]*)"
```

**Comment by elliotchance** [comment]
Wow, it would be great if you took a time before and after. Also since we are caching the regexp now I wonder how much benefit it would give.

I'm very confident with the the AST tests so feel free to mess around as much as you want with the regex in the `act` package 👍

**Comment by yulvil** [comment]
While looking at this issue I noticed that some regex are missing the type2 `(:'(?P<type2>.*)')?`.

The regex are greedy so the type becomes `struct s':'struct s`.

I guess the code is working because we do not use the type for those node types. Something to investigate.

```
BinaryOperator 0x55fd3df303f0 <line:118:5, col:21> 'struct s':'struct s' '='
ArraySubscriptExpr 0x55b9783b61d8 <col:390, col:396> 'struct s':'struct s' lvalue
```
