### ISSUE TITLE
Ignore C code from Github statistic

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#319]
Now, we see 14% of C code, but that code is only for test:
![screenshot at 2017-11-03 12 40 34](https://user-images.githubusercontent.com/16690032/32367772-5979637c-c094-11e7-8dc0-825a06b63c95.png)

But in according to https://medium.com/black-tech-diva/how-to-change-repo-language-in-github-c3e07819c5bb and https://github.com/github/linguist#overrides:
we can create a file `.gitattributes`:
```
tests/* linguist-vendored
```
then we can ignore C code from Github statistic.

Feel free to close that issue.

**Comment by elliotchance** [comment]
Thanks. I have updated the previous release to also contain this issue number.
