### ISSUE TITLE
extern definitions confuse c2go

### ISSUE THREAD

**Issue by djadala** [elliotchance/c2go#328]
Hi,
this simple example reproduce issue,
t.c:
```C
#include<stdio.h>

extern int array[];
int array[4] = { 1, 2, 3, 4 };

int main() {
	printf("%d",array[1]) ;
     return 0;
}
```
may be extern declarations can be ignored ?

**Comment by elliotchance** [comment]
Hi @djadala can you please provide the output that shows the error?

**Comment by djadala** [comment]
And sorry for not providing detailed explanation in 1st comment.

**Comment by elliotchance** [comment]
The solution should be simple. To ignore any variable declaration where https://github.com/elliotchance/c2go/blob/16715db94709be807d88ab64019d0af53eaa67e4/ast/var_decl.go#L14 is `false`.

Perhaps ignore the case here? https://github.com/elliotchance/c2go/blob/master/transpiler/variables.go#L275-L283

**Comment by djadala** [comment]
> Perhaps ignore the case here?

I add ```if a.IsExtern``` in variables.go:

```go
case *ast.VarDecl:
		    if a.IsExtern {
				continue
			}
```

and try to transpile t.c, but results are same.
After some investigation i concluded that even function transpileDeclStmt is not called. ( i insert panic  as 1st statement. And removed binary c2go before every recompilation)

Do you have any idea ?

**Comment by elliotchance** [comment]
Sorry, I pointed you to the wrong function. `VarDecl` is handled by `transpileVarDecl` (I should know that 😛 ): https://github.com/elliotchance/c2go/blob/3b0663ee2f9c0858371525d9250c4c4d5bbbcf61/transpiler/declarations.go#L214

Try something like this:

```go
func transpileVarDecl(p *program.Program, n *ast.VarDecl) (
	[]goast.Stmt, []goast.Stmt, string) {
	// Ignore extern as there is no analogy for Go right now.
	if n.IsExtern {
		return nil, nil, ""
	}

	// There are cases where the same variable is defined more than once. I
	// assume this is because they are extern or static definitions. For now, we
	// will ignore any redefinitions.
	if _, found := p.GlobalVariables[n.Name]; found {
		return nil, nil, ""
	}
```

**Comment by djadala** [comment]
Yes, this works perfectly, either in applied test case, and in large C code base where i hit this problem.
I discovered new typedef problem, will open new issue.

**Comment by djadala** [comment]
Not new issue, actually i found #265

**Comment by Konstantin8105** [comment]
Present Go result from same C code:
```go
var array interface {
}
var array []int = []int{1, 2, 3, 4}

func main() {
        __init()
        noarch.Printf([]byte("%d\x00"), array[1])
        return
}
```
