### ISSUE TITLE
Debug perfomance: Clang

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#349]
### Problem
Now, `preprocessor` for each run `go test -tag=ingeration` use `clang` for build AST tree of C source.
Preliminary, it is take 30% of time.
### Solution
Create in `/tmp/` specific caches.
Preliminary steps:
1) Create a folder `/tmp/clang-ast/`
2) User run `c2go transpile ...` or `go test -tag=ingeration` 
3) Preprocessor create a copy of user C source in temp folder ( for example : `tmp/clang-ast/1` ).
4) Preprocessor calculate a hash of C source file and saved in folder ( for example : `.../1/hash.txt`).
5) Preprocessor convert C source to AST tree and saved in forlder (for example: `.../1/ast.txt`).
6) Preprocessor saved file about success (for example: `...1/done`).
7) Next work like usually.

For next running:
Preprocessor check have cached ast tree and if hash is same, then used prepared ast tree.

(+/-) If you reboot, then all cached file are lost. And it is Ok.

**Comment by Konstantin8105** [comment]
Examples for hash calculation:
https://golang.org/pkg/crypto/md5/
https://golang.org/pkg/crypto/sha256/

**Comment by Konstantin8105** [comment]
If you want free reboot and don't lost cached files, then we can create a specific variable environment with folder of cached files

**Comment by Konstantin8105** [comment]
for more effective - we can move that code `preprocessor`:
https://github.com/elliotchance/c2go/blob/a7ac059fc71fcdf75704c6f8061cb796e4d342ee/main.go#L208-L235

**Comment by elliotchance** [comment]
I'm fine with this, but only for testing. Do not cache anything when its running under production.

**Comment by Konstantin8105** [comment]
@elliotchance , Could you approve next?
If you haven't specific environment variables like "C2GO_CACHE_PREPROCESSOR=~/CACHE/", then all work like usually.
But if you add, then cache is switch on.
Is it ok?

**Comment by Konstantin8105** [comment]
After experiments with cache:
* If create cache only for `clang` - it is save ~5...10 % of time
* For save >50% of time need caching next part of code:
https://github.com/elliotchance/c2go/blob/dca511cd9ab171795c7fb27e8412a62a175e5099/main.go#L204-L275

**Comment by Konstantin8105** [comment]
Performance test.
```
 2017-11-29 10:07:40 ⌚  konstantin-VirtualBox in ~/go/bin/sqlite
○ → time c2go transpile sqlite3.c

real	0m5.110s
user	0m8.616s
sys	0m0.964s

 2017-11-29 10:08:07 ⌚  konstantin-VirtualBox in ~/go/bin/sqlite
○ → time c2go transpile sqlite3.c

real	0m3.951s
user	0m7.776s
sys	0m0.752s
```
Saved 20...30% of time

**Comment by Konstantin8105** [comment]
After thinking #384, that caching is not effective.
