### ISSUE TITLE
Debug performance: Flag

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#350]
Please check - is that flag are really need?
https://github.com/elliotchance/c2go/blob/769de31b59436c55f110921feafbc9df320e69ce/main_test.go#L130-L135

Because, we have for travis:
https://github.com/elliotchance/c2go/blob/769de31b59436c55f110921feafbc9df320e69ce/travis/test.sh#L37

If we remove flag `-race` from file `main_test.go`, then debugging will be faster. About other - I don't know.

**Comment by elliotchance** [comment]
* `-cover*` settings are required for the code coverage.
* `-race` does make the testing slower is safer.

**Comment by Konstantin8105** [comment]
At the true , before debug , I always commented that lines :), but after return back.

Ok, Thank you. We can close that issue
