### ISSUE TITLE
Multifiles C code to single Go code

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#362]
Now, we have the problem in multifile transpilation is separating `#define` on each file.
**Solution**
Example : `c2go transpile 1.c 2.c 3.c ....`
1) Find all definition for `1.c` like that:
```
clang -dM -E  1.c
```
Output:
```
#define BUFSIZ _IO_BUFSIZ
#define EOF (-1)
#define FILENAME_MAX 4096
#define FOPEN_MAX 16
#define L_ctermid 9
#define L_tmpnam 20
#define NULL ((void*)0)
...
```
2) Transfer definition to file 2.c. Used `-D` of clang.
3) ...
Link for help: https://clang.llvm.org/docs/ClangCommandLineReference.html#dumping-preprocessor-state

Main task for issue: Transling sqlite files `shell.c` and `sqlite3.c` in one.

> Last trying: https://github.com/Konstantin8105/c2go/blob/e70dfa5765eff7e05fdefaa754bf5c62b4a3986b/travis/test.sh

**Comment by elliotchance** [comment]
There is only two ways to transpile multiple files correctly:

1. Merge all of the C files into a single C file to preprocess and transpile, resulting in one large Go file. (This is what we do as of v0.17.0).
2. Transpile each C file completely independently (they do not affect each other at all) generating one Go file for each input C file. Then we remove the duplicated after the Go is produced. This is where we hope to get to. See https://github.com/elliotchance/c2go/issues/232#issuecomment-346494921.
