### ISSUE TITLE
Example addition for switch statements

### ISSUE THREAD

**Issue by carstenhag** [elliotchance/c2go#43]
Tried to transpile a simple program with a switch statement and it failed with the following error:
`panic: Unknown node type: 'SwitchStmt 0x55c465236c38 <line:10:3, line:23:3>'`

switch.c
```c
#include <stdio.h>

int main() {
  
  int num;
  printf("Give me either an 1 or a 2: ");
  scanf("%d", &num);

  switch(num) {
    case 1:
      printf("1\n");
      break;
    case 2:
      printf("2\n");
      break;
    default:
      printf("Invalid input.\n");
      break;
  }
}
```

**Comment by elliotchance** [comment]
Please place the sample above into `tests/misc/switch.c` and get Travis passing 😄
