### ISSUE TITLE
Example addition for stdbool.h / _Bool panic

### ISSUE THREAD

**Issue by carstenhag** [elliotchance/c2go#44]
Panics when finding _Bool type: `panic: '_Bool'`

stdbool.c
```c
#include <stdio.h>
#include <stdbool.h>

int main() {
  
  bool trueBool = true;
  bool falseBool = false;
    
  if(trueBool) {
    printf("true bool\n");
  }
  
  if(!falseBool) {
    printf("reversed false bool\n");
  }
  
}
```

**Comment by elliotchance** [comment]
This is probably the easiest header to implemented.

For anything that wants to pickup this task, please put the above code into `tests/stdbool/stdbool.c` and make Travis pass :)

**Comment by elliotchance** [comment]
#65
