### ISSUE TITLE
function f(){} not acceptable for Go

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#470]
c:
```c
void F(){
};
```
error: `missing return at end of function`
Correct Go code:
```go
func F(){
    return
}
```

**Comment by elliotchance** [comment]
I don't understand, why is Go requiring the return statement?

**Comment by Konstantin8105** [comment]
It is `go build` error, so for Go it is important.
I will check later, for next C code:
```c
int fff(int i){
    if (i > 5) {
        return 0;
    }
/// No another case
}
```

**Comment by Konstantin8105** [comment]
Need for #67

**Comment by Konstantin8105** [comment]
Another C example:
```c
int f(int a){
if (a > 5){
    return 0;
} else {
    return -1;
}
// for C no need return here, but for Go it is important
}
```
### Solution
add `return MAGIC_NUMBER` for example : `-4222` depend of return type.
