### ISSUE TITLE
Proposal: Debug tool, Approve tool - Indication of transpilation correctness

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#600]
After transpilation, we will have a just Go file.
How to check result of transpilation?
Simple way is "Create a tests and execute C and Go program - and compare the result."
It is possible only all is Ok.
What we will do, if Go program is not correct transpiled?
For example, after execute Go program - program is not finalize.
How to localize the bug?
The way  like read Go and try to found - it is not a simple, for example if your Go code have 10000 code lines.

One of ways is - add to source some indicators of work.
Let's look on example:
```c
int main()
{
    int i = 0;
    if (i >= 0)
    {
        printf("Hello world");
    }
    return 0;
}
```
After complilation we will see:
```
Hello world
```
For indicator, for example, we will use `printf` injected in C code before `}` and after `{` or after `;`, but not inside `"text { text text } text"` and not inside `struct` or `union`.
Let's look on our example:
```c
int main()
{
    printf("00001");
    int i = 0;
    if (i >= 0)
    {printf("00002");
        printf("Hello world");
    printf("00003");}
    return 0;
printf("00004");}
```
After compilation we will see:
```
00001
00002
Hello world
00003
```
Much more information.
If we will see after execute Go version with indicators:
```
00001
00002
00002
00002
00002
00002
00002
00002
Hello world
00003
```
or:
```
00001
00002
00002
00002
00002 
... and infinite 00002
```
So, Go version is not identical.

Limit:
* Each indicator MUST be uniq
* Indicator can use one or more ways like: print in stdout, print in file, print in stderr...
* Execution without any flag
* In C code cannot be `#include` with absolute path
* Application MUST work not infinite time (but Go application can work infinite, so need timeout for break) 
* Application cannot be concurrency
* Indicators is allowable only inside functions.
* Default folder for indicator work in `/tmp/indicator/`

Prototype:
```
c2go transpile -analyze 1.c 2.c
```
Prototype of result:
```
# Creating copy of : 1.c 2.c
# Add indicators in :
#     1.c
#     2.c
# Execution C application
# Found 1023 indicators in C application
# Transpilation to Go code
# Execution Go application
# Found 1223 indicators in Go application
# See report in folder : /tmp/indicator/
```

**Comment by Konstantin8105** [comment]
Same indicator list in C and Go is not enough for success.
Also we know all added indicators. So if in indicator list found all added indicator, so indicator code coverage is good.

**Comment by elliotchance** [comment]
This makes sense. Theres a few things:

1. The integer markers would be more helpful if they described the location, such as the function name and line number. This would be much easier to follow than an integer and would also make more sense if there were changes to the C code.

2. "analyse" is not the right term, "debug" makes more sense. Rename the CLI flag `-debug`.

3. Need an option to specify where the output goes, right now stdout and stderr make sense but if they want it to goto a specific file then there should be another CLI option, like `-debug-file=/tmp/foo`.

**Comment by Konstantin8105** [comment]
That issue can be closed, because the task is too big.

**Comment by elliotchance** [comment]
I am closing this because the PR was closed with an explanation.
