### ISSUE TITLE
Jsonnet

### ISSUE THREAD

**Issue by gedw99** [elliotchance/c2go#62]
Thanks for this project.

I am wondering if it's nuts to try to convert this :
https://github.com/google/jsonnet

I am not a c programmer but can hack my way through it so it's hard for me to judge if a library as complex as jsonnet is too big a leap.

The reason i want a golang version is because kubernetes uses this to driver configuration codegen.

https://github.com/kubernetes/kubernetes-anywhere

**Comment by elliotchance** [comment]
At the moment there is still a lot of work to be done with c2go just to get the core parts of C implemented. Support for C++ would take a lot more effort on top of that.

**Comment by gedw99** [comment]
Ah. We should wait then.
