### ISSUE TITLE
Compiling multiple files

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/c2go#63]
At the moment all the preprocessed code is output into a single Go file. If there were multiple files process you would get lots of duplicate symbols in the same package.

**Comment by cristim** [comment]
Would it work if it transpiled the C source files one to one to corresponding Go files which would then be compiled together?

It should also somehow handle subdirectories, like creating them in golang as sub-packages.

**Comment by elliotchance** [comment]
One solution is to preprocess all input files together and output a single Go file. The advantage is its simple, easy and should word. The disadvantage is that you will end up with one truely enormous Go file for a decent sized library that will be difficult to maintain. It will also not be possible to combine multiple translations together because all the duplicate symbols.
