### ISSUE TITLE
Hex encoded literal has bad AST

### ISSUE THREAD

**Issue by kamphaus** [elliotchance/c2go#663]
If I have the following test:

### cast2.c
```c
#include "tests.h"

typedef unsigned int pcre_uint32;
#define CHAR_NBSP                   ((unsigned char)'\xa0')

void test_cast()
{
    int tmp = 160;
    pcre_uint32 chr = tmp;

    is_eq(chr, CHAR_NBSP);
}

int main()
{
    plan(1);

    diag("Compare preprocessor with type")

    test_cast();

    done_testing();
}
```
I can execute it with `clang -lm -o main cast2.c && ./main` and obtain:
```
1..1
# Compare preprocessor with type
1 ok - chr == CHAR_NBSP
```
However with c2go (`c2go transpile -o main.go -p main cast2.c && go run main.go`) I obtain:
```
# command-line-arguments
./main.go:335:67: syntax error: unexpected %, expecting expression
./main.go:341:5: syntax error: unexpected ), expecting := or = or comma
./main.go:344:55: syntax error: unexpected newline, expecting { after if clause
./main.go:349:4: syntax error: unexpected else after top level declaration):
```
The problem is that `CHAR_NBSP` has been transpiled as `(uint8(%!q(int=4294967200)))`.
While debugging I found that the AST node for it is:
```
|   | | |-ImplicitCastExpr 0x5583de4b9090 <col:24, col:48> 'double' <IntegralToFloating>
|   | | | `-ParenExpr 0x5583de508550 <col:24, col:48> 'unsigned char'
|   | | |   `-ParenExpr 0x5583de508530 <col:25, col:47> 'unsigned char'
|   | | |     `-CStyleCastExpr 0x5583de508508 <col:26, col:41> 'unsigned char' <IntegralCast>
|   | | |       `-CharacterLiteral 0x5583de5084e0 <col:41> 'int' 4294967200
```
Is this a bug in clang?

**Comment by elliotchance** [comment]
That's an interesting catch. On first glance it does look like a bug in clang.

As I write this I think I understand the issue. It is being encoded as a 4 byte character, ie:

(92 * 256^3) + (120 * 256^2) + (97 * 256^1) + (48 * 256^0) = 1,551,393,072

OK... maybe not.

---

There was an issue a while back where all floating-points were stored in the AST output as 6 significant figures, which wasn't accurate enough to do any reliable math calculations. The only solution was to use the positional information and physically read the original value from the preprocessed file.

We could follow the same process for extracting floating-points: https://github.com/elliotchance/c2go/blob/master/ast/floating_literal.go#L66-L114

**Comment by kamphaus** [comment]
While a process similar as for extracting floating-points would work, it is not trivial, since there doesn't seem to be a ready-made parser for C character literal expressions (for floats we could just use `fmt.Sscan`).

We would have to implement a scanner for character literals ourself maybe based on [clang](http://llvm.org/svn/llvm-project/cfe/trunk/lib/Lex/LiteralSupport.cpp) (cf. CharLiteralParser::CharLiteralParser).
A way to do write a parser in Go can be found here: http://grokbase.com/t/gg/golang-nuts/138nm6p640/go-nuts-do-we-have-c-parser-in-go-already

It would have to follow the C specification:
http://en.cppreference.com/w/cpp/language/character_literal
http://en.cppreference.com/w/cpp/language/escape
The parsed literal then needs to be transformed into an integer value.

Is there no way to tell clang to include the correct value in the AST?

**Comment by cznic** [comment]
@kamphaus 

> We would have to implement a scanner for character literals ourself maybe based on clang (cf. CharLiteralParser::CharLiteralParser).

You might want to take a look at [charConst](https://github.com/cznic/sqlite2go/blob/6617e2aad08549d18787027028562d701f44cbb0/internal/c99/encoding.go#L302). Please feel free to use it if it may possibly suit your needs. Or possibly also any other code from the `c99` package, for that matter.

**Comment by elliotchance** [comment]
@kamphaus yes, I see it would be more difficult - but nothing is impossible ;)

Unfortunately there are not real options for the clang AST, and there are several little bugs throughout (and across versions of clang). I think it's mainly used as a debugging tool for the parser which we are repurposing way beyond what it was originally intended for.
