### ISSUE TITLE
"Project Progress" link in the README doesn't work

### ISSUE THREAD

**Issue by opennota** [elliotchance/c2go#665]
https://github.com/elliotchance/c2go/wiki/Project-Progress doesn't exist and redirects to the wiki index page: https://github.com/elliotchance/c2go/wiki

**Comment by elliotchance** [comment]
Thanks, that approach (trying to document everything that is and isn't supported) turned out to be too hard to maintain. Especially since the project is so young and so many things are changing.

I will remove it from the README.
