### ISSUE TITLE
print(--r) turns into print(r -= 1), which is invalid

### ISSUE THREAD

**Issue by 131072** [elliotchance/c2go#673]
print(--r) should translate to print(r - 1) instead

**Comment by elliotchance** [comment]
Thanks for raising this issue, I had also discovered it recently. This was previously working but the mechanism to determine whether expressions should be wrapped in closures was broken along the way.

**Comment by kamphaus** [comment]
Should be fixed with e1f3d1276c8aec504410c901f4d4c07c0eb56c86
