### ISSUE TITLE
Conversion of bool to int32 Performs Poorly

### ISSUE THREAD

**Issue by jcburley** [elliotchance/c2go#795]
Use of `map[bool]int32{false: 0, true: 1}[bool-expr]` showed up in my profiling as a major consumer of CPU time.

I suggest using `func(val) int32 { if val { return 1 } else { return 0 } }(bool-expr)` instead.

Consider the following program:

```
package main

import "flag"
import "fmt"
import "math/rand"
import "os"
import "time"

var n_iterations int = 1 * 1000 * 1000
var hits int
var imp string

// Ideal conversion:
func f_bool(n int) bool {
	return n == 42
}

func f_int(n int) int32 {
	if f_bool(n) {
		return 1
	} else {
		return 0
	}
}

// c2go conversion (current):
func f_int_via_map(n int) int32 {
	return map[bool]int32{false: 0, true: 1}[n == 42]
}

// c2go conversion (proposed):
func f_int_via_func(n int) int32 {
	return func() int32 { if n == 42 { return 1 } else { return 0 } }()
}

func main() {
	var f func (int) int32
	flag.Parse()
	switch imp {
	case "bool":
		f = f_int
	case "int_via_map":
		f = f_int_via_map
	case "int_via_func":
		f = f_int_via_func
	default:
		fmt.Fprintf(os.Stderr, "Invalid implementation `%s'.\n", imp)
		os.Exit(1)
	}
	
	random := rand.New(rand.NewSource(time.Now().UnixNano()))
	for i := 0; i < n_iterations; i += 1 {
		if f(random.Intn(100)) != 0 {
			hits += 1
		}
	}
	fmt.Fprintf(os.Stdout, "imp=%s n_iterations=%d hits=%d\n", imp, n_iterations, hits)
}

func init() {
	flag.StringVar(&imp, "implementation", "bool", "Specify implementation to use: 'bool', 'int_via_map', or 'int_via_func'")
	flag.IntVar(&n_iterations, "iterations", 1 * 1000 * 1000, "Specify number of iterations to run")
}
```

The runtimes on my Ubuntu 16.04 machine (with an i7-2600; it's about seven years old) suggest the proposed `func` conversion is about as fast as the ideal (direct-to-bool) conversion, while the current conversion (using `map`) is several times slower:

```
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation bool -iterations $((10 * 1000 * 1000))
imp=bool n_iterations=10000000 hits=100002

real	0m0.288s
user	0m0.288s
sys	0m0.000s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation bool -iterations $((10 * 1000 * 1000))
imp=bool n_iterations=10000000 hits=99791

real	0m0.289s
user	0m0.288s
sys	0m0.000s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation int_via_func -iterations $((10 * 1000 * 1000))
imp=int_via_func n_iterations=10000000 hits=100108

real	0m0.295s
user	0m0.292s
sys	0m0.000s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation int_via_func -iterations $((10 * 1000 * 1000))
imp=int_via_func n_iterations=10000000 hits=100309

real	0m0.287s
user	0m0.284s
sys	0m0.000s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation int_via_func -iterations $((10 * 1000 * 1000))
imp=int_via_func n_iterations=10000000 hits=99742

real	0m0.295s
user	0m0.292s
sys	0m0.000s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation int_via_map -iterations $((10 * 1000 * 1000))
imp=int_via_map n_iterations=10000000 hits=100125

real	0m1.366s
user	0m1.364s
sys	0m0.000s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation int_via_map -iterations $((10 * 1000 * 1000))
imp=int_via_map n_iterations=10000000 hits=100485

real	0m1.368s
user	0m1.364s
sys	0m0.004s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$ time ./cast -implementation int_via_map -iterations $((10 * 1000 * 1000))
imp=int_via_map n_iterations=10000000 hits=100081

real	0m1.372s
user	0m1.364s
sys	0m0.004s
craig@doe:~/.go/src/github.com/jcburley/cast (master #)$
```

**Comment by jcburley** [comment]
I don't seem to have perms to push a branch (and thus a PR, maybe because I cloned rather than forked?) to this repo, but the change I made (to `types/cast.go`) is quite simple:

```
			//e := util.NewGoExpr(`map[bool]int32{false: 0, true: 1}[replaceme]`)
			e := util.NewGoExpr(`func(val bool) int32 { if val { return 1 } else { return 0 } }(replaceme)`)
```

Note that this does seem to pass `go test -integration` (as well as the original, a caveat being that I get a failure on `assert.c` on _both the original and my changed version_ due to lack of any output, which I can't seem to figure out).

**Comment by elliotchance** [comment]
Are you receiving an error when trying to open the PR?

**Comment by jcburley** [comment]
No, I get it when trying to push my branch:

craig@pony:~/.go/src/github.com/elliotchance/c2go <http://github.com/elliotchance/c2go> (faster-int-to-bool)$ git push -u origin faster-int-to-bool 
ERROR: Permission to elliotchance/c2go.git denied to jcburley.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
craig@pony:~/.go/src/github.com/elliotchance/c2go <http://github.com/elliotchance/c2go> (faster-int-to-bool)$ gitrem
origin	git@github.com <mailto:git@github.com>:elliotchance/c2go (fetch)
origin	git@github.com <mailto:git@github.com>:elliotchance/c2go (push)
craig@pony:~/.go/src/github.com/elliotchance/c2go <http://github.com/elliotchance/c2go> (faster-int-to-bool)$ git fetch origin
craig@pony:~/.go/src/github.com/elliotchance/c2go <http://github.com/elliotchance/c2go> (faster-int-to-bool)$ git pull origin master
From github.com <http://github.com/>:elliotchance/c2go
 * branch            master     -> FETCH_HEAD
Already up to date.
craig@pony:~/.go/src/github.com/elliotchance/c2go <http://github.com/elliotchance/c2go> (faster-int-to-bool)$

(I guess it isn’t easy being green! Though that background color might not show up in github….)

**Comment by jcburley** [comment]
Whoa, that got badly formatted! Here is the tty session, entered via the github website itself rather than via reply to email:

```
craig@pony:~/.go/src/github.com/elliotchance/c2go (faster-int-to-bool)$ git push -u origin faster-int-to-bool 
ERROR: Permission to elliotchance/c2go.git denied to jcburley.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
craig@pony:~/.go/src/github.com/elliotchance/c2go (faster-int-to-bool)$ gitrem
origin	git@github.com:elliotchance/c2go (fetch)
origin	git@github.com:elliotchance/c2go (push)
craig@pony:~/.go/src/github.com/elliotchance/c2go (faster-int-to-bool)$ git fetch origin
craig@pony:~/.go/src/github.com/elliotchance/c2go (faster-int-to-bool)$ git pull origin master
From github.com:elliotchance/c2go
 * branch            master     -> FETCH_HEAD
Already up to date.
craig@pony:~/.go/src/github.com/elliotchance/c2go (faster-int-to-bool)$ 
```

**Comment by jcburley** [comment]
Nevermind, I just realized I was erroneously trying to push my new branch directly to your project, rather than to my fork, which I'd created awhile back and forgot about completely. (Been working mostly on my own repos, on github and on my private git server, so got used to working directly with the upstream repo....)

PR should be available now.
