### ISSUE TITLE
Q: Why is $GOPATH always requried

### ISSUE THREAD

**Issue by hajimehoshi** [elliotchance/c2go#797]
Hi,

Awesome project! Using C with Cgo is always painful in terms of compilation time, so your project would be really helpful.

I tried to use c2go, but go a warning:

```
Error: The $GOPATH must be set
```

As Go 1.11 now supports modules, there are some people like me who don't use `$GOPATH`. I was wondering why `$GOPATH` is required, and if this could be eliminated in the future.

Thanks!

**Comment by elliotchance** [comment]
The original ticket that raised that error was #168. However, it doesn't seem to related.

Perhaps try commenting out that line and running it again? I'm not sure why it was original required.

**Comment by hajimehoshi** [comment]
I think it worked, but am not sure.
