### ISSUE TITLE
can't convert open62541.c

### ISSUE THREAD

**Issue by eugeis** [elliotchance/c2go#802]
Hello, 
I am trying to transpile [open62541.c](https://github.com/open62541/open62541/releases/download/0.3-rc2/open62541.c) on MacOs.

I am geting following exceptions

Any chance todo it or it is too difficult for now?
Thank You

c2go transpile open62541.c
panic: could not match regexp with string
^(?P<address>[0-9a-fx]+) (?:prev (?P<prev>0x[0-9a-f]+) )?(?:parent (?P<parent>0x[0-9a-f]+) )?<(?P<position>.*)>(?P<position2> .+:\d+)?(?P<used> used)?(?P<referenced> referenced)?(?P<name> \w+)? '(?P<type>.+?)'(?P<type2>:'.*?')?(?P<extern> extern)?(?P<static> static)?(?P<cinit> cinit)?(?P<register> register)?[\s]*$
0x7feb6d06b2e8 <col:5, col:21> col:21 used result 'UA_BrowseResult':'UA_BrowseResult' nrvo

goroutine 23 [running]:
github.com/elliotchance/c2go/ast.groupsFromRegex(0xc00739d900, 0x13b, 0xc005f61300, 0x5a, 0xc005f612ca)
	/Users/ee/go/src/github.com/elliotchance/c2go/ast/ast.go:286 +0x379
github.com/elliotchance/c2go/ast.parseVarDecl(0xc005f61300, 0x5a, 0x1295a6b)
	/Users/ee/go/src/github.com/elliotchance/c2go/ast/var_decl.go:26 +0x65
github.com/elliotchance/c2go/ast.Parse(0xc005f612f8, 0x62, 0x1294a14, 0x5)
	/Users/ee/go/src/github.com/elliotchance/c2go/ast/ast.go:252 +0x46c
main.convertLinesToNodes(0xc001507b60, 0x392c, 0x15708, 0x0, 0x0, 0x0)
	/Users/ee/go/src/github.com/elliotchance/c2go/main.go:89 +0x1cf
main.convertLinesToNodesParallel.func1.1(0xc0007f60c0, 0xc00000c008, 0xc001507b60, 0x392c, 0x15708, 0x0)
	/Users/ee/go/src/github.com/elliotchance/c2go/main.go:113 +0x59
created by main.convertLinesToNodesParallel.func1
	/Users/ee/go/src/github.com/elliotchance/c2go/main.go:111 +0x112

**Comment by elliotchance** [comment]
This should be quite easy to resolve, see a similar PR issue here: https://github.com/elliotchance/c2go/issues/799
