### ISSUE TITLE
how to work on windows?

### ISSUE THREAD

**Issue by ddkwork** [elliotchance/c2go#857]

**Comment by elliotchance** [comment]
I have not tried it on windows. Are you encountering an error?

**Comment by DiskGetor** [comment]
> 我没有在Windows上尝试过。您遇到错误了吗？

sorry，i do not known how to install clang on windows.

**Comment by elliotchance** [comment]
I do not know how to install clang on windows, but this might be a good place to start: https://clang.llvm.org/get_started.html

**Comment by ivanjaros** [comment]
i downloaded the win64 precompiled binary but when i run c2go i will get `clang: warning: unable to find a Visual Studio installation`, so clang is not enough and one needs to download the entire VS ffs.

**Comment by caerbannogwhite** [comment]
I'd suggest using the WSL
https://docs.microsoft.com/en-us/windows/wsl/install
