### ISSUE TITLE
Installation of c2go

### ISSUE THREAD

**Issue by g41797** [elliotchance/c2go#894]
First of all - thanks a lot for this code

go get -u github.com/elliotchance/c2go
Result:
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,

Worked installation: 
go install github.com/elliotchance/c2go@latest
go build github.com/elliotchance/c2go

Is it possible to add clarification?
Thanks

**Comment by g41797** [comment]
OOOOPS
Just now I got the point - PR is "pull request" :-(
I started to learn git some days ago and still don't understand acronyms

Moreover all linux tools are new for me
e.g. c2go requires clang - i spend long time to install it
next step - compilation flags for include dirs 
I cannot find example of c2go cmd line with -I 
etc etc

**Comment by ohjiwoo123** [comment]
Thanks for notice that how to install newly!
