### ISSUE TITLE
Is it possible to convert .cpp aswell?

### ISSUE THREAD

**Issue by the-hotmann** [elliotchance/c2go#897]
I wanted to do some testings on converting this WinRAR KeyGen, which is c++ (cpp) based: https://github.com/bitcookies/winrar-keygen into pure GoLang. But it includes `.hpp`, `.cpp`, `.h` files, but no `.c` files.

Is it possible, if so, how/where to start? As I am not a C++ programmer I would like to ask upfront, before wasting time doing it wrong.

**Comment by elliotchance** [comment]
This wont be possible. This package only handles C and is not mature enough to handle complex projects.
